name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  checks:
    runs-on: codeberg-small
    container:
      image: nixos/nix:latest
    defaults:
      run:
        shell: sh

    steps:
      - name: Install CI prerequisites
        run: |
          mkdir -p /etc/nix
          printf '%s\n' 'experimental-features = nix-command flakes' > /etc/nix/nix.conf
          nix profile add nixpkgs#nodejs

      - name: Check out repository
        uses: https://data.forgejo.org/actions/checkout@v4

      - name: Run checks
        run: nix flake check path:$PWD
